#!/usr/bin/env bash
# The script to display "Best School" 10 times using while loop

count=1
while [ $count -le 10 ] 
do
    echo "Best School"
    #count=$(( count + 1))
    ((count++)) # I can get to use both
done
