#!/usr/bin/env bash
# The script to display 4 as bad luck and 8 as good luck then the rest as Best School

count=1
while [ $count -le 10 ]
do 
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
