#!/usr/bin/env bash
# Updates hostfile to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8
# (To be run in Docker container; else revert hostfile back)
# https://web.archive.org/web/20171117023601/http://blog.jonathanargentiero.com/docker-sed-cannot-rename-etcsedl8ysxl-device-or-resource-busy/

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
